# Importando e Criando Banco de Dados

In [1]:
# Importando as bibliotecas necessárias
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect

In [2]:
engine = create_engine("sqlite:///:memory")  # Substitua pelo seu banco de dados

In [3]:
# Código omitido

url = "https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv"

In [ ]:
import pandas as pd

dados = pd.read_csv(url)  # Lê o arquivo CSV diretamente da URL
dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [6]:
engine = create_engine("sqlite:///clientes.db")  # Substitua pelo seu banco de dados

inspector = inspect(engine)

print(inspector.get_table_names())

["clientes.db"]

[]


['clientes.db']

In [ ]:
# Salva o DataFrame como tabela 'clientes' no banco de dados, se ainda não existir
dados.to_sql("clientes", engine, if_exists="replace", index=False)

query = "SELECT * FROM clientes WHERE Categoria_de_renda= 'Empregado'"
empregados = pd.read_sql(query, engine)  # Lê os dados filtrados

In [ ]:
empregados.to_sql("empregados", con=engine, index=False, if_exists="replace")

226059

In [16]:
pd.read_sql_table(
    "empregados",
    con=engine,
    columns=["ID_Cliente", "Grau_escolaridade", "Rendimento_anual"],
)  # Lê a tabela 'empregados' do banco de dados e a armazena em um DataFrame

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

#  Métodos atualizados para interação com o banco de dados

Após ler todos os registros da tabela clientes, é fundamental iniciar importando a função text do SQLAlchemy. Esta função é essencial para criar e executar expressões SQL literais dentro do seu código Python. Ao utilizar text, você pode inserir diretamente instruções SQL que o SQLAlchemy compreenderá e executará:

In [17]:
from sqlalchemy import text

Para deletar um registro na tabela clientes, agora utilizamos a seguinte estrutura:

In [18]:
query = "DELETE FROM clientes WHERE ID_Cliente=5008804"
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

Vamos quebrar o código em partes para entender melhor cada etapa:

Definição da consulta SQL: Primeiro, definimos o que queremos fazer com o banco de dados em uma string de consulta SQL, armazenada na variável query. Aqui, o comando DELETE é usado para remover o registro de um cliente específico, identificado pelo ID_Cliente=5008804.

Estabelecendo conexão com o banco de dados: Usamos with engine.connect() as conn para abrir uma conexão com o banco. O with é muito útil porque gerencia automaticamente a abertura e o fechamento da conexão. Isso significa que, após o bloco de código ser executado, a conexão será fechada automaticamente, evitando que recursos sejam desperdiçados ou bloqueios no banco de dados se prolonguem.

Executando a consulta: Dentro do bloco with, executamos a consulta com conn.execute(text(query)). A função text() é usada aqui para garantir que a string de consulta seja interpretada como SQL puro.

Confirmar a transação: Por fim, chamamos conn.commit() para confirmar a transação. Isso é crucial porque, em muitos bancos de dados, as alterações feitas (como deletar um registro) não são salvas permanentemente até que sejam confirmadas explicitamente.

Este processo garante que o registro seja removido de forma segura e eficiente, minimizando a possibilidade de erros ou problemas de segurança.

De maneira similar, para atualizar informações de um registro, como o grau de escolaridade de um cliente, você pode proceder da seguinte forma:

In [19]:
query = (
    'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
)
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

Aqui, a conexão é estabelecida novamente, a consulta de atualização é executada para alterar o grau de escolaridade do cliente com ID 5008808 para "Ensino superior", e a transação é confirmada.

Estes passos são cruciais para manipular dados de forma segura e eficaz, utilizando as funcionalidades mais recentes do SQLAlchemy

In [24]:
pd.read_sql_table("clientes", engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]