In [ ]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect

engine = create_engine("sqlite:///:memory:")

In [23]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv"
dados = pd.read_csv(url)
dados.to_sql("clientes", engine, index=False)

438463

In [ ]:
pd.read_sql_table("clientes", engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [25]:
from sqlalchemy import text

Criar o banco de dados local com a biblioteca SQLAlchemy.
Escrever os dados do arquivo CSV neste banco de dados local.
Realizar três atualizações no banco de dados:
Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

Criar um novo registro de cliente seguindo as especificações abaixo:

ID_Cliente: 6850985

Idade: 33

Grau_escolaridade: Doutorado

Estado_civil: Solteiro

Tamanho_familia: 1

Categoria_de_renda: Empregado

Ocupacao: TI

Anos_empregado: 2

Rendimento_anual: 290000

Tem_carro: 0

Moradia: Casa/apartamento próprio

In [ ]:
# Atualizar o banco de dados, ID cliente 6840104 com redimento anual de 300000

# Conexão com o banco de dados
engine = create_engine("sqlite:///dados_clientes.db")
# engine = create_engine("mysql+pymysql://root:senha@localhost/dados_clientes")
inspector = inspect(engine)

print(inspector.get_table_names())

[]


['clientes.db']

In [ ]:
# Certifique-se de que a tabela 'clientes' existe no banco de dados
dados_clientes.to_sql("clientes", engine, if_exists="replace", index=False)

query = "UPDATE clientes SET Rendimento_anual=300000 WHERE ID_Cliente=6840104"
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()
# Verificando se o valor foi atualizado
query = "SELECT * FROM clientes WHERE ID_Cliente=6840104"
with engine.connect() as conn:
    result = conn.execute(text(query))
    for row in result:
        print(row)

(6840104, 62, 'Ensino médio', 'Divorciado', 1, 'Pensionista', 'Outro', 0, 300000.0, 0, 'Casa/apartamento próprio')


In [ ]:
# Excluir o registro do cliente de ID 5008809
query = "DELETE FROM clientes WHERE ID_Cliente=5008809"
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()
# Verificando se o valor foi atualizado
query = "SELECT * FROM clientes WHERE ID_Cliente=5008809"

In [ ]:
# Criar um novo registro de cliente
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'
# Verificando se o valor foi atualizado
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()
# Verificando se o valor foi atualizado
query = "SELECT * FROM clientes WHERE ID_Cliente=6850985"
with engine.connect() as conn:
    result = conn.execute(text(query))
    for row in result:
        print(row)

(6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000.0, 0, 'Casa/apartamento próprio')
(6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000.0, 0, 'Casa/apartamento próprio')
(6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000.0, 0, 'Casa/apartamento próprio')


In [21]:
query = "SELECT * FROM clientes WHERE ID_Cliente=6850985"
pd.read_sql_table("clientes", engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   
438462     6850985     33         Doutorado       Solteiro                1   
438463     6850985     33         Doutorado       Solteiro                1   
438464     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0                 Empregado      Outro              12          427500.0   
1                 Empregado      Outro              12          427500.0   
2                 Empregado  Segurança               3          112500.0   
3       Associado comercial     Vendas               8          270000.0   
4       Associado comercial     Vendas               8          270000.0   
...                     ...        ...             ...               ...   
438460          Pensionista      Outro               0           72000.0   
438461            Empregado     Vendas               3          121500.0   
438462            Empregado         TI               2          290000.0   
438463            Empregado         TI               2          290000.0   
438464            Empregado         TI               2          290000.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               0  Casa/apartamento próprio  
4               0  Casa/apartamento próprio  
...           ...                       ...  
438460          0  Casa/apartamento próprio  
438461          0  Casa/apartamento próprio  
438462          0  Casa/apartamento próprio  
438463          0  Casa/apartamento próprio  
438464          0  Casa/apartamento próprio  

[438465 rows x 11 columns]